# Generated by Django 3.2.22 on 2023-11-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='board.Tag', verbose_name='タグ'),
        ),
    ]
