# Generated by Django 3.2.22 on 2023-11-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
