# Generated by Django 3.2.22 on 2023-11-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20231201_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='Taging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.post', verbose_name='掲示物')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.tag', verbose_name='タグ')),
            ],
        ),
    ]
