# Generated by Django 3.2.22 on 2023-11-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_tag_taging'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taging',
        ),
    ]
