# Generated by Django 3.2.22 on 2023-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='board.Tag', verbose_name='学年タグ'),
        ),
    ]
